version: "3.7"

services:
  web:
    image: nginx:1.21-alpine
    container_name: interns2022b-web
    working_dir: /application
    restart: unless-stopped
    tty: true
    volumes:
      - .:/application
      - ./environment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${EXTERNAL_WEBSERVER_PORT}:80"

  php:
    image: ghcr.io/blumilksoftware/php:8.1
    container_name: interns2022b-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
